# Use a Node.js base image
FROM node:20-alpine

# Create and set the working directory
WORKDIR /app

# Copy the rest of the application code
COPY . .

# Install dependencies
RUN npm install

# Expose the port your application runs on (optional)
EXPOSE 8080

# Command to run the application
CMD ["node", "index.js"]

