apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mosquitto-config.yaml
  - mosquitto-password.yaml
  - mosquitto-service.yaml
  - mosquitto-pv-claim.yaml
  - mosquitto-deployment.yaml