apiVersion: v1
kind: Service
metadata:
  name: batch-processor-service
  namespace: iotproject
spec:
  selector:
    app: batch-processor
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP