apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |
    # Mosquitto MQTT Broker Configuration

    # Listening on port 1883, on all network interfaces
    listener 1883 0.0.0.0

    # Bridge configuration
    bridge_max_packet_size 0

    # TLS/SSL settings (optional, configure only if using encrypted communication)

    # Path to CA certificate for verifying remote broker's server certificate
    bridge_cafile /etc/mosquitto/certs/ca.crt

    # Path to directory containing CA certificates
    bridge_capath /etc/mosquitto/certs

    # If using certificate-based authentication, specify the client certificate and key
    bridge_certfile /etc/mosquitto/certs/client.crt
    bridge_keyfile /etc/mosquitto/certs/client.key

    # Uncomment if using PSK-based encryption
    # bridge_identity my-psk-identity
    # bridge_psk abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890

    # External configuration files
    include_dir /etc/mosquitto/conf.d