apiVersion: apps/v1
kind: Deployment
metadata:
  name: hivemq
  labels:
    app: hivemq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hivemq
  template:
    metadata:
      labels:
        app: hivemq
    spec:
      containers:
      - name: hivemq
        image: hivemq/hivemq4:latest 
        ports:
        - containerPort: 1883 
        - containerPort: 8080 

---
apiVersion: v1
kind: Service
metadata:
  name: hivemq-service
spec:
  type: NodePort
  ports:
  - name: mqtt
    port: 1883
    targetPort: 1883
    protocol: TCP
    nodePort: 30011 
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 30012
  selector:
    app: hivemq