apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
    - protocol: TCP
      nodePort: 30092
      port: 9092
      targetPort: 9092

---
# apiVersion: v1
# kind: Service
# metadata:
#   name: zookeeper-service
# spec:
#   type: NodePort
#   selector:
#     app: zookeeper
#   ports:
#     - protocol: TCP
#       nodePort: 30093
#       port: 2181
#       targetPort: 2181


apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper-service
  name: zookeeper-service
spec:
  type: NodePort
  ports:
    - name: zookeeper-port
      port: 2181
      nodePort: 30181
      targetPort: 2181
  selector:
    app: zookeeper

